version: '3.4'

services:
  mysql_db:
    #image: mysql:8
    image: mariadb:10
    environment:
      - MYSQL_USER=guest
      - MYSQL_PASSWORD=fGHAFSDfgasfdhfADSta¨&%¨&%JAHSD
      - MYSQL_ROOT_PASSWORD=ajhsdfaghsfd&%¨DAS76u
      - MYSQL_DATABASE=teste
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

volumes:
  mysql_data:
    driver: local       