version: '3.4'

services:
  postgresql_db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=teste
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - rede

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 80:80
    networks:
      - rede

volumes:
  postgres_data:
    driver: local       

networks:
  rede:
    driver: bridge